### ISSUE TITLE
implicitly satisfied requirements

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/authserver#12]
If it turns out that the Module does not have any implicitly satisfied requirements (because all required dependencies are explicitly met), should we keep the appendix (for consistent section labeling with other Modules) and just have stub text about how all dependencies are explicitly satisfied?

**Comment by ajlaing** [comment]
Don't see a benefit to having implicit requirements.

**Comment by jfisherbah** [comment]
Github conversion will adopt latest module template which includes a section for implicit requirements. If it's null, there will just be a stub. Closing.
