### ISSUE TITLE
randomly generated PSK

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/authserver#13]
SME feedback says that PSKs should be randomly generated and there should be an appropriate requirement that covers this. 

FCS_RADSEC_EXT.1.2 allows for the generation of PSKs using the DRBG claimed in FCS_RBG_EXT.1. Does this sufficiently cover this or would it be preferable to re-factor the SFRs to put the PSK generation in the actual PSK SFR (since there may be non-RADIUS uses of generated PSKs)?

**Comment by ajlaing** [comment]
PSK used for EAP-TLS (or EAP-TTLS) in RADIUS/DIAMETER will be consistent with the options (generated random, derived PW, OTP)  being worked in the VPN PP modules. For Generated random PSK, reference to FCS_RBG_EXT.1 is preferable to hinting that the TSF should have its own RBG.

See #15 regarding PSK in RADSEC.

**Comment by jfisherbah** [comment]
The existence of FIA_PSK_EXT.2 appears to resolve this. Closing.
