### ISSUE TITLE
supported groups extension requirement

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/authserver#8]
Our understanding is that the use of ffdhe groups in the TLS Supported Groups extension is recommended. Is it acceptable to add these as a selection to FCS_EAP-TLS_EXT.1.7* and then put in an app note that support for them is encouraged?

*note the specific way this gets implemented will depend on how other comments on FCS_EAP-TLS_EXT.1 are resolved. This issue is more for general acceptance of the notion that EAP-TLS should make support for ffdhe* groups selectable, with an app note promoting their use.

**Comment by ajlaing** [comment]
We'll migrate to Supported Groups ffdhe requirements consistent with the TLS package/base SFR. The easiest path for this is to reference, not redefine TLS SFR.

**Comment by jfisherbah** [comment]
Acknowledged that the "base" TLS requirements are now inherited from the NDcPP so there is no need to redefine. Closing.
